spring:
    datasource:
        # Docker Compose 서비스 이름 'db'를 사용하도록 변경
        url: jdbc:mysql://db:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
        username: root # docker-compose.yml의 MYSQL_USER 또는 MYSQL_ROOT_PASSWORD와 일치
        password: 1234 # docker-compose.yml의 MYSQL_PASSWORD 또는 MYSQL_ROOT_PASSWORD와 일치
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            # 'update' : 실행 시 없으면 자동으로 @Entity붙은 도메인 클래스명으로 테이블 생성(데이터 생성 X)
            ddl-auto: update
        show-sql: true          # 실행되는 SQL 쿼리를 로그에 표시
        properties:
            hibernate:
                format_sql: true   # SQL 쿼리를 포맷하여 보기 좋게 출력
                dialect: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true   # 하이버네이트(JPA)의 DDL(테이블) 생성이 완료된 후, data.sql를 실행하도록 설정

    # src/main/resources/경로에 data.sql이 있을 시 해당 파일의 SQL 구문이 자동으로 실행 ★★
#    sql:
#        init:
#            mode: always

logging:
    level:
        org:
            springframework:
                security: DEBUG

# =============== 외부 이미지 업로드 경로 설정 ===============
# 이 부분은 각 개발자가 자신의 PC 환경에 맞게 수정하여 사용합니다.
custom:
    # Windows 사용자 예시:
    upload-path: C:/Devel/Izic/prac_toon/toon_uploads/images/
    # macOS 또는 Linux 사용자 예시 (필요시 주석 해제 후 사용):
    # upload-path: /Users/YourUsername/toon_uploads/
# ============================ ===========================